spring:
  application:
    name: aggregator
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: ${SPRING_CLOUD_CONFIG_FAIL_FAST:false}
      retry:
        useRandomPolicy: true
        max-interval: 6000
        max-attempts: 6
      discovery:
        enabled: ${SPRING_CLOUD_CONFIG_DISCOVERY_ENABLED:true}
        serviceId: ${SPRING_CLOUD_CONFIG_DISCOVERY_SERVICE_ID:config-server}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    fetch-registry: ${EUREKA_CLIENT_FETCH_REGISTRY:true}
    register-with-eureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
    non-secure-port: ${EUREKA_INSTANCE_NON_SECURE_PORT:${server.port}}
    non-secure-port-enabled: true
    secure-port-enabled: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90