server:
  port: 0

grpc:
  server:
    port: 0

spring:
  application:
    name: collector

collector:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        client.id: "stats.collector"
        key.serializer: org.apache.kafka.common.serialization.LongSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        user-actions: stats.user-actions.v1

logging:
  level:
    ru.yandex.practicum: INFO
    ru.yandex.practicum.service: DEBUG
    ru.yandex.practicum.kafka: DEBUG
    org.springframework: WARN
    org.springframework.boot: INFO
    org.springframework.web: WARN
    org.apache.kafka: INFO
    org.apache.kafka.clients: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: ERROR
    io.grpc: INFO
    net.devh.boot.grpc: INFO
    org.apache.avro: WARN