server:
  port: 0

spring:
  application:
    name: aggregator

aggregator:
  kafka:
    producer:
      properties:
        bootstrap.servers: localhost:9092
        client.id: "stats.aggregator"
        key.serializer: org.apache.kafka.common.serialization.LongSerializer
        value.serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
      topics:
        events-similarity: stats.events-similarity.v1
    consumer:
      properties:
        bootstrap.servers: localhost:9092
        group.id: aggregator-group
        key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
        value.deserializer: ru.yandex.practicum.kafka.deserializer.UserActionDeserializer
        auto.offset.reset: latest
        enable.auto.commit: false
      topics:
        user-actions: stats.user-actions.v1

logging:
  level:
    ru.yandex.practicum: INFO
    ru.yandex.practicum.service: DEBUG
    ru.yandex.practicum.kafka: DEBUG
    org.springframework: WARN
    org.springframework.boot: INFO
    org.springframework.web: WARN
    org.apache.kafka: INFO
    org.apache.kafka.clients: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: ERROR
    io.grpc: INFO
    net.devh.boot.grpc: INFO
    org.apache.avro: WARN