server:
  port: 0

grpc:
  server:
    port: 0

spring:
  application:
    name: analyzer
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7432/recommendationsdb
    username: dbuser
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

hibernate:
  jdbc:
    time_zone: UTC

analyzer:
  kafka:
    consumer-actions:
      properties:
        bootstrap.servers: localhost:9092
        group.id: analyzer-actions-group
        key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
        value.deserializer: ru.yandex.practicum.kafka.deserializer.UserActionDeserializer
        auto.offset.reset: earliest
        enable.auto.commit: false
      topics:
        user-actions: stats.user-actions.v1
    consumer-similarities:
      properties:
        bootstrap.servers: localhost:9092
        group.id: analyzer-similarities-group
        key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
        value.deserializer: ru.yandex.practicum.kafka.deserializer.EventSimilarityDeserializer
        auto.offset.reset: earliest
        enable.auto.commit: false
      topics:
        events-similarity: stats.events-similarity.v1

logging:
  level:
    ru.yandex.practicum: INFO
    ru.yandex.practicum.service: DEBUG
    ru.yandex.practicum.kafka: DEBUG
    org.springframework: WARN
    org.springframework.boot: INFO
    org.springframework.web: WARN
    org.apache.kafka: INFO
    org.apache.kafka.clients: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: ERROR
    io.grpc: INFO
    net.devh.boot.grpc: INFO
    org.apache.avro: WARN