grpc:
  client:
    collector:
      address: static://collector:9090
    analyzer:
      address: static://analyzer:9090

server:
  port: 0

stats-server:
  name: stats-server

spring:
  application:
    name: event-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/eventdb
    username: dbuser
    password: 12345
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

hibernate:
  jdbc:
    time_zone: UTC

logging:
  level:
    ru.practicum: TRACE
    org.springframework.orm.jpa: INFO
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE